name: asynCmd g++
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Compile
      run: |
        cd ./asynCmd
        g++ --static -std=c++11 asyncMD.cpp -o asynCmd -pthread
        mv ./asynCmd ../asynCmd.lexe
        cd ..
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
      # Artifact name
        name: linuxBuild
      # A file, directory or wildcard pattern that describes what to upload
        path: ./asynCmd.lexe
